---
title: "Smoking Behaviour in Five British Cohort Studies"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(DT)
df <- readRDS("smoking_items.Rds")
```

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r, echo = FALSE}
tags$style(HTML("
  .download-button {
    display: inline-block;
    padding: 10px 15px;
    font-size: 16px;
    color: white;
    background-color: #007BFF; /* Bootstrap primary color */
    border: none;
    border-radius: 5px;
    text-decoration: none;
    margin: 5px 0;
  }

  .download-button:hover {
    background-color: #0056b3; /* Darker shade for hover effect */
  }
"))

tabsetPanel(
  # First tab - Introduction
  tabPanel("Introduction",
           br(),
           includeMarkdown("introduction.md"),
           br(),
           div(
             style = "display: flex; justify-content: flex-end;",
             HTML('<a href="smoking_items.xlsx" download>Download Database as Excel file</a>')
           )
  ),
  # Second tab - Interactive Table
  tabPanel("Database",
           br(),
           div(
             style = "display: flex; justify-content: flex-end;",
             HTML('<a href="smoking_items.xlsx" download>Download Database as Excel file</a>')
           ),
           br(), br(),
           datatable(df, 
                     escape = FALSE,
                     filter = 'top',
                     options = list(
                       pageLength = 500,
                       searchHighlight = TRUE,
                       scrollX = TRUE,
                       autoWidth = TRUE,
                       dom = 'Bfrtip',
                       selection = 'single'
                     )
           )
  )
)
``` 

